In [1]:
import pandas as pd
import numpy as np 
import nltk 
from gensim.models import word2vec
from sklearn.feature_extraction.text import TfidfVectorizer
import spacy

In [2]:
review_data = pd.read_csv('../data/processed_data/drugsComTrain_text_preprocessing.csv')

In [3]:
review_data.head()

,Unnamed: 0,Unnamed: 0.1,drug_id,drugName,condition,review,rating,date,usefulCount,lowered_review,...,stemmed_review,lemmatized_review,review_len,stemmed_review_len,lem_review_len,word_count,sentiment_vader,sentiment_vader_label,sentiment_textblob,sentiment_textblob_label
0,0,0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9.0,2012-05-20,27,"""it has no side effect, i take it in combinati...",...,no side effect take combin bystol mg fish oil,no side effect take combin bystol mg fish oil,46,45,45,9,-0.2960,Negative,0.000000,neutral
1,1,1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8.0,2010-04-27,192,"""my son is halfway through his fourth week of ...",...,son halfway fourth week intuniv becam concern ...,son halfway fourth week intuniv becam concern ...,372,369,367,65,0.6929,Positive,0.114583,positive
2,2,2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5.0,2009-12-14,17,"""i used to take another oral contraceptive, wh...",...,use take anoth oral contracept pill cycl happi...,use take anoth oral contracept pill cycl happi...,403,401,401,70,0.2732,Positive,0.105000,positive
3,3,3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8.0,2015-11-03,10,"""this is my first time using any form of birth...",...,first time use form birth control glad went pa...,first time use form birth control glad went pa...,226,223,225,39,0.1027,Positive,0.300000,positive
4,4,4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9.0,2016-11-27,37,"""suboxone has completely turned my life around...",...,suboxon complet turn life around feel healthie...,suboxon complet turn life around feel healthie...,380,378,379,58,0.8934,Positive,0.147037,positive

In [4]:
column_names=['sentiment_vader_label','sentiment_textblob_label','remove_punctuation_review','drug_id','drugName','condition','rating','usefulCount']
review_data_new = review_data[column_names]

In [5]:
review_data_new.head()

,sentiment_vader_label,sentiment_textblob_label,remove_punctuation_review,drug_id,drugName,condition,rating,usefulCount
0,Negative,neutral,it has no side effect i take it in combination...,206461,Valsartan,Left Ventricular Dysfunction,9.0,27
1,Positive,positive,my son is halfway through his fourth week of i...,95260,Guanfacine,ADHD,8.0,192
2,Positive,positive,i used to take another oral contraceptive whic...,92703,Lybrel,Birth Control,5.0,17
3,Positive,positive,this is my first time using any form of birth ...,138000,Ortho Evra,Birth Control,8.0,10
4,Positive,positive,suboxone has completely turned my life around ...,35696,Buprenorphine / naloxone,Opiate Dependence,9.0,37

Word Embeddings:

Tf_idf

In [6]:
tf_idf = TfidfVectorizer()

In [7]:
tfidf_matrix = tf_idf.fit_transform(review_data_new['remove_punctuation_review'])

In [8]:
tfidf_matrix.get_shape()

(160392, 82266)

In [9]:
feature_names = tf_idf.get_feature_names_out()

RECOMMENDATION FUNCTION

In [11]:
def userful_count(data,feature):
 max_value = data[feature].max()
 min_value = data[feature].min()
 data[feature] = (data[feature] - min_value) / (max_value - min_value)
 return data

In [12]:
def recom_sys (condition,label):
    data = userful_count(review_data,'usefulCount') 
    data['rec_score'] = (data[label]) * data['usefulCount']
    score = data[data['condition']==condition].sort_values(by=['rec_score'],ascending=False)
    return score['drugName'].unique()

In [13]:
condition = input('give condition name')
label = input ('select from the following: sentiment_vader or sentiment_textblob')
recom_sys(condition,label)

array(['Mirena', 'Levonorgestrel', 'Implanon',
       'Ethinyl estradiol / etonogestrel', 'Etonogestrel',
       'Loestrin 24 Fe', 'Lo Loestrin Fe',
       'Ethinyl estradiol / levonorgestrel', 'Aviane', 'NuvaRing',
       'Ethinyl estradiol / norethindrone', 'Levora', 'Copper', 'Lutera',
       'Nexplanon', 'Ethinyl estradiol / norelgestromin',
       'Drospirenone / ethinyl estradiol / levomefolate calcium', 'Beyaz',
       'Medroxyprogesterone', 'Depo-Provera', 'Ortho Tri-Cyclen Lo',
       'Ethinyl estradiol / norgestimate', 'Sprintec', 'Seasonique',
       'Orsythia', 'Ortho Tri-Cyclen', 'Lybrel', 'Norethindrone',
       'Ortho Micronor', 'Ortho Evra', 'Junel Fe 1 / 20', 'Nora-Be',
       'Yaz', 'Drospirenone / ethinyl estradiol', 'TriNessa', 'Yasmin',
       'Microgestin Fe 1 / 20', 'Generess Fe', 'Tri-Sprintec', 'Falmina',
       'Errin', 'LoSeasonique', 'Apri', 'Mono-Linyah', 'Ocella',
       'Cryselle', 'Ethinyl estradiol / norgestrel', 'Gianvi', 'Chateal',
       'Alesse', 'Sronyx', 'Jolivette', 'ParaGard',
       'Desogestrel / ethinyl estradiol', 'Mononessa', 'Xulane',
       'Gildess Fe 1 / 20', 'Microgestin Fe 1.5 / 30', 'Camila', 'Kariva',
       'Ortho Cyclen', 'Minastrin 24 Fe', 'Estarylla',
       'Gildess Fe 1.5 / 30', 'Loestrin 21 1 / 20', 'Skyla', 'Zarah',
       'Jolessa', 'Heather', 'Blisovi 24 Fe', 'Reclipsen', 'Tri-Previfem',
       'Quasense', 'Microgestin 1 / 20', 'Taytulla', 'Natazia', 'Portia',
       'Trivora', 'Camrese', 'Seasonale', 'Aubra', 'Lyza',
       'Ortho-Novum 7 / 7 / 7', 'Azurette', 'Kyleena',
       'Blisovi Fe 1 / 20', 'Tri-Lo-Sprintec', 'Safyral', 'Necon 1 / 35',
       'Viorele', 'Desogen', 'Sharobel', 'Liletta', 'Ortho-Novum 1 / 35',
       'Nortrel 7 / 7 / 7', 'Dienogest / estradiol', 'Altavera',
       'Tarina Fe 1 / 20', 'Zovia', 'Ethinyl estradiol / ethynodiol',
       'Loryna', 'Marlissa', 'Femcon Fe', 'Ortho-Cept', 'Mircette',
       'Velivet', 'Blisovi Fe 1.5 / 30', 'Cyred',
       'Depo-Provera Contraceptive', 'Junel Fe 1.5 / 30', 'Vienva',
       'Elinest', 'Lo / Ovral-28', 'Lessina', 'Larin Fe 1 / 20',
       'Tri-Estarylla', 'Amethia', 'Lo / Ovral', 'Cyclessa', 'Introvale',
       'Rajani', 'Levlen', 'Alyacen 1 / 35', 'Plan B', 'Tri-Linyah',
       'Nortrel 1 / 35', 'Junel 1 / 20', 'Briellyn', 'Previfem',
       'Ogestrel-28', 'Loestrin Fe 1 / 20', 'Amethia Lo', 'Ashlyna',
       'Nikki', 'Zovia 1 / 35',
       'Ethinyl estradiol / folic acid / levonorgestrel', 'CamreseLo',
       'TriNessa Lo', 'Tri-Lo-Marzia', 'Balziva', 'Gildess 24 Fe',
       'Junel Fe 24', 'Philith', 'Dasetta 1 / 35', 'Pirmella 1 / 35',
       'Cyclafem 1 / 35', 'Larissia', 'Junel 1.5 / 30',
       'Microgestin 1.5 / 30', 'Enskyce', 'Caziant', 'Norlyda',
       'Gildess 1 / 20', 'Mibelas 24 Fe', 'Mestranol / norethindrone',
       'Necon 1 / 50', 'Zenchent', 'Provera', 'Lomedia 24 Fe', 'Lillow',
       'Gildess 1.5 / 30', 'Juleber', 'depo-subQ provera 104',
       'Loestrin Fe 1.5 / 30', 'Necon 7 / 7 / 7', 'Larin 24 Fe',
       'Amethyst', 'Tri-Lo-Estarylla', 'Vestura', 'Loestrin 21 1.5 / 30',
       'Pimtrea', 'Jencycla'], dtype=object)